language: ruby
sudo: false
before_install:
  - gem update bundler
cache: bundler
matrix:
  include:
    - rvm: 2.4.9
    - rvm: 2.5.7
    - rvm: 2.6.5
    - rvm: jruby-9.2.9.0
    - rvm: 2.6.5
      install: true # This skips 'bundle install'
      script: gem build *.gemspec && gem install *.gem
notifications:
  email: false
