language: ruby
before_install:
  - gem update bundler
cache: bundler
matrix:
  include:
    - rvm: 2.5.8
    - rvm: 2.6.6
    - rvm: 2.7.1
    - rvm: jruby-9.2.11.1
    - rvm: 2.7.1
      install: true # This skips 'bundle install'
      script: gem build *.gemspec && gem install *.gem
notifications:
  email: false
