language: ruby
sudo: false
before_install:
  - gem update bundler
cache: bundler
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.0.5.0
  - jruby-9.1.15.0
notifications:
  email: false
