name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        ruby: [3.1, 3.2, 3.3, jruby-9.3.14, jruby-9.4.7]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
